version: 2
jobs:
  job_a:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: touch a
          command: |
            mkdir -p workspace/a
            touch workspace/a/100
            echo "export A=100" >> $BASH_ENV
      - run:
          name: echo
          command: |
            echo $A
      - persist_to_workspace:
          root: workspace
          paths:
            - a

  job_b:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: touch b
          command: |
            mkdir -p workspace/b
            touch workspace/b/200
      - persist_to_workspace:
          root: workspace
          paths:
            - b

  job_c:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: touch c
          command: |
            mkdir -p workspace/c
            touch workspace/c/300
      - persist_to_workspace:
          root: workspace
          paths:
            - c

  job_d:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}
      - run:
          name: touch d
          command: |
            ls -R
            mkdir -p workspace/d
            touch workspace/d/400
      - save_cache:
          key: v1-{{ arch }}
          paths:
            - workspace

  job_e:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: list dir contains
          command: |
            ls -R

  job_f:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}
      - run:
          name: restore and list contains
          command: |
            ls -R

  list:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: echo
          command: |
            echo $A
      - run:
          name: list dirs
          command: |
            ls -R workspace

workflows:
  version: 2
  build_and_test:
    jobs:
      - job_a
      - job_b
      - job_c
      - job_d
      - job_e:
          requires:
            - job_a
      - job_f
      - list:
          requires:
            - job_a
            - job_b
            - job_c
