version: 2

shared-steps: &shared-steps
  - checkout
  - run:
      name: say hello
      command: |
        echo 'hello'

jobs:
  job_a:
    docker:
      - image: circleci/node:8
    steps:
      - <: *shared-steps
      - run:
          name: touch a
          command: |
            mkdir -p workspace/a
            touch workspace/a/100
      - persist_to_workspace:
          root: workspace
          paths:
            - a

  job_b:
    docker:
      - image: circleci/node:8
    steps:
      - <: *shared-steps
      - run:
          name: touch b
          command: |
            mkdir -p workspace/b
            touch workspace/b/200
      - persist_to_workspace:
          root: workspace
          paths:
            - b

  job_c:
    docker:
      - image: circleci/node:8
    steps:
      - <: *shared-steps
      - run:
          name: touch c
          command: |
            mkdir -p workspace/c
            touch workspace/c/300
      - persist_to_workspace:
          root: workspace
          paths:
            - c
  list:
    docker:
      - image: circleci/node:8
    steps:
      - <: *shared-steps
      - attach_workspace:
          at: workspace
      - run:
          name: list dirs
          command: |
            ls -R workspace

workflows:
  version: 2
  build_and_test:
    jobs:
      - job_a
      - job_b
      - job_c
      - list:
          requires:
            - job_a
            - job_b
            - job_c
